name: Build VMDK Lib
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: libyal/libvmdk
          ref: 20240510
      - name: install_dependencies
        run: sudo apt-get -y install autoconf automake autopoint build-essential git libfuse3-dev
      - name: Generate libvmdk
        run: |
          ./synclibs.sh 
          ./autogen.sh
          ./configure --prefix=${{ github.workspace }}/build
          make
          make install
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/build
          retention-days: 1
