name: Tsk-Net - Build & Pack

on: [push]
env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-aff:
    uses: ./.github/workflows/build-aff-lib.yml
    with:
      artifact-name: afflib
  build-ewf:
    uses: ./.github/workflows/build-ewf-lib.yml
    with:
      artifact-name: ewflib