name: Tsk-Net - Build & Pack

on: [push]
env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build-aff:
    uses: ./.github/workflows/build-aff-lib.yml
    with:
      artifact-name: afflib
  build-ewf:
    uses: ./.github/workflows/build-ewf-lib.yml
    with:
      artifact-name: ewflib
  build-vhdi:
    uses: ./.github/workflows/build-vhdi-lib.yml
    with:
      artifact-name: vhdilib
  build-vmdk:
    uses: ./.github/workflows/build-vmdk-lib.yml
    with:
      artifact-name: vmdklib
  build-slvm:
    uses: ./.github/workflows/build-slvm-lib.yml
    with:
      artifact-name: slvm
  build-bfio:
    uses: ./.github/workflows/build-bfio-lib.yml
    with:
      artifact-name: bfio