name: Build bfio Lib
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: libyal/libbfio
          ref: 20240414
      - name: install_dependencies
        run: sudo apt install git autoconf automake autopoint libtool pkg-config
      - name: Generate libbfio
        run: |
          ./synclibs.sh 
          ./autogen.sh
          ./configure --prefix=${{ github.workspace }}/build
          make
          make install
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ github.workspace }}/build
          retention-days: 1
